### ISSUE TITLE
How to use opt-mhm to calculate the specific heat of a system

### ISSUE THREAD

**Issue by TienMPhan** [tbereau/opt-mhm#1]
Hi Tristan,

I am working on a system using your generic CG model, J Chem Phys 130, 235106 (2009). After running parallel tempering simulations, I want to calculate the specific heat of the system like the way you did in Fig.11 in the paper and I intend to use `opt-mhm` to do this task. When reading the options by executing `opt-mhm` without arguments, I'm not sure  how the program works. For example, after running remd using `peptideB` with `Espresso`, we have multiple "temp-folders" with `observables.dat`, `histogram.dat` and configuration files in each. How can we feed the data files in `opt-mhm` to calculate the free energy and specific heat? Could you give some tips on this?

Thank you very much.

-Martin-

**Comment by tbereau** [comment]
Hi Martin,

It's quite easy:
1) Make sure your `observables.dat` files (you can rename them) have the following structure:
```
 Time		Energy
```
where energy is the potential energy of the system (output by `peptideB` and units of kT).
2) Create one `metafile.dat` which contains the paths to the different replicas
```
 Path_i		Temperature_i		Snapshot_i	  autocor_factor_i
```
as explained in the README of https://github.com/tbereau/opt-mhm.
3) Run `opt-mhm`
4) You'll get some output files, one containing both `<E>` and `<E^2>` (it's called `temp_avg1.dat` or something like that). You can use that to compute the specific heat.
5) If you want a free energy as a function of a specific reaction coordinate, redo step 1-4 but changing your `observables.dat` file to include the time series of the reaction coordinate between `time` and `energy` (see README). You'll then need to use the argument `-q1` to output the free energy as a function of that order parameter.

**Comment by TienMPhan** [comment]
Thanks for being so helpful. Now I can make it run. I just want to be sure a few things about the information that we put in the `metafile.dat`,

`Snapshot_i`, the first snapshot using in sampling. For example, if we run parallel tempering with `polyala.tcl` in `peptideB` examples, the first snapshot in each folder should be `polyala.vmd0000.pdb`. Is it correct?

`autocoor_factor_i`, an  integer that specifies how many files should be taken into account. For example, if I run 10 different temperatures in parallel tempering, there are 10 `observables.dat` files so I should put `autocor_factor_i=10` for each `i`? Or we can put any number there? I tried to put some different values, it didn't affect the result in `temp_avg.dat`. One more thing, should `autocor_factor_i`  be the same for each `i`?

**Comment by tbereau** [comment]
If I remember correctly, `snapshot_i` requires a number, which is in units of `Time` in the `observables.dat` file. If you leave it out, then it takes the entire dataset into consideration.

`autocor_factor_i` is also optional: if you set 10, then it means you only read 1 datapoint every 10 along each time series. That's just to avoid highly correlated data. Note, however, that taking into account correlated data does not hurt WHAM, especially away from phase transitions. If there are large _variations_ in the autocorrelation time, this may bias your results.

**Comment by tbereau** [comment]
So indeed, you can put different numbers if you have an estimate of the autocorrelation time for each replica.

**Comment by TienMPhan** [comment]
Yeah, I see. You are so patient and helpful. Thanks for making so many software packages publicly available.
